[build]
builder = "NIXPACKS"
buildCommand = "cd donutmcstore_new/project && npm install && npm run build"

[deploy]
startCommand = "cd donutmcstore_new/project && npm run preview"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/"
timeout = 10
